# using this code we'll understand padding 

In [30]:
import tensorflow as tf 

x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

x = tf.reshape(x, [1, 2, 3, 1])  # give a shape accepted by tf.nn.max_pool

valid_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
same_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='SAME')

valid_pad.get_shape() == [1, 1, 1, 1]  # valid_pad is [5.]
same_pad.get_shape() == [1, 1, 2, 1]   # same_pad is  [5., 6.]


x1 = tf.constant([[1., 2., 3. ,4.],
                 [4., 5., 6. ,7.]])

x1=tf.reshape(x1 , shape=[1,2,4,1])
valid_pad_ = tf.nn.max_pool(x1, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
same_pad_ = tf.nn.max_pool(x1, [1, 2, 2, 1], [1, 2, 2, 1], padding='SAME')

sess=tf.Session()
print sess.run(valid_pad)
print sess.run(same_pad)


print sess.run(valid_pad_)
print sess.run(same_pad_)

[[[[ 5.]]]]
[[[[ 5.]
   [ 6.]]]]
[[[[ 5.]
   [ 7.]]]]
[[[[ 5.]
   [ 7.]]]]


In [20]:
x = tf.constant( [[1,2,3]
                ,[4,5,6]])

x= tf.reshape(x , [1,2,3,1])
valid_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
same_pad = tf.nn.max_pool( x, [1,2,2,1] , [1,2,2,1] , padding = 'SAME')

valid_pad.get_shape() ==[1,1,1,1]
same_pad.get_shape() ==[1,1,2,1]




TypeError: DataType int32 for attr 'T' not in list of allowed values: float32, float16

In [21]:
x = tf.constant( [[1,2,3]
                ,[4,5,6]])

valid_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
same_pad = tf.nn.max_pool( x, [1,2,2,1] , [1,2,2,1] , padding = 'SAME')

valid_pad.get_shape() ==[1,1,1,1]
same_pad.get_shape() ==[1,1,2,1]




ValueError: Cannot reshape a tensor with 6 elements to shape (1, 2, 2, 1) (4 elements)

In [23]:
x = tf.constant( [[1.,2.,3.]
                ,[4.,5.,6.]])

valid_pad = tf.nn.max_pool(x, [1, 2, 2, 1], [1, 2, 2, 1], padding='VALID')
same_pad = tf.nn.max_pool( x, [1,2,2,1] , [1,2,2,1] , padding = 'SAME')

valid_pad.get_shape() ==[1,1,1,1]
same_pad.get_shape() ==[1,1,2,1]




ValueError: Shape must be rank 4 but is rank 2